CREATE TABLE regions (
code INTEGER PRIMARY KEY,
nom VARCHAR NOT NULL
) ;

CREATE TABLE departements (
code VARCHAR PRIMARY KEY,
region INTEGER REFERENCES regions (code) ON DELETE SET NULL,
nom VARCHAR NOT NULL
) ;

CREATE TABLE communes (
code VARCHAR PRIMARY KEY,
departement VARCHAR REFERENCES departements (code) ON DELETE SET NULL,
nom VARCHAR
) ;

CREATE TABLE sites (
idSite VARCHAR PRIMARY KEY,
nom VARCHAR NOT NULL,
codeCommune VARCHAR REFERENCES communes (code) ON DELETE CASCADE,
dateDeclaration DATE NOT NULL,
typeEau VARCHAR NOT NULL,
longitude DOUBLE PRECISION NOT NULL,
latitude DOUBLE PRECISION NOT NULL
) ;

CREATE TABLE evenements (
idEvenement INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
idSite VARCHAR REFERENCES sites (idSite) ON DELETE CASCADE,
evenement VARCHAR,
debut DATE,
fin DATE,
mesure VARCHAR
) ;

CREATE TABLE analyses (
idAnalyse INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
idSite VARCHAR REFERENCES sites (idSite) ON DELETE CASCADE,
datePrelevement DATE NOT NULL,
enterocoques INTEGER NOT NULL,
escherichia INTEGER NOT NULL
) ;
